const treatments = [
    'Relationship Therapy',
    'Pre-marital Therapy',
    'Sexless Relationship',
    'Sexual Harassment Counselling',
    'Sexual orientation counselling',
    'Puberty Counselling',
    'Body Image Counselling',
    'Porn Addiction',
    'Masturbation Addiction',
    'Sex Addiction',
    'Sexual Phobias (M)',
    'Sexual Phobias (F)',
    'Erectile Dysfunction',
    'Premature Ejaculation',
    'Difficulty Having Orgasm (F)',
    'Low Sex Drive (M)',
    'Low Sex Drive (F)',
    'Painful Sex (M)',
    'Painful Sex (F)',
    'STDs and STIs',
    'Infertility',
    'Sexless Relationship',
    'Painful Period',
    'Irregular Period',
    'Abnormal Vaginal Discharge',
    'Curved or Painful Erection',
    'Nightfall',
    'Vaginismus',
    'Semen in Urine (Dhat)',
    'PCOD or PCOS',
    'Abnormal Penile Discharge',
    'Painful Ejaculation',
    'Foreskin Problem (Phimosis)',
    'Blood in Ejaculation',
    'Prolonged Erection (Priapism)',
    'Relationship Therapy',
    'Pre-marital Therapy',
    'Genital Surgery Counselling',
    'Sexual Harassment Counselling',
    'Sexual orientation counselling',
    'Family planning counselling',
    'Puberty Counselling',
    'Body Image Counselling',
    'Endometriosis',
    'Porn Addiction',
    'Masturbation Addiction',
    'Sex Addiction',
    'Sexual Phobias (M)',
    'Sexual Phobias (F)',
    'Genital Infection',
    'Pain During Urination',
    'Blood in Urine',
    'Frequent Urination',
    'Urinary Tract Infection (UTI)',
    'Pelvic Inflammatory Disease',
    'Abnormal Breast Discharge',
    'Orgasmic Flu - POIS (M)',
    'Orgasmic Flu - POIS (F)',
    'HIV',
    'Delayed Ejaculation (M)',
];

module.exports.treatments = treatments;
